2021-12-23 15:46:15,569 - ERROR - Row 4
Traceback (most recent call last):
  File "C:\Users\Matthew Curtis\Documents\Github-Pipl\Tests\Full Featured Example\Python CSV script Example - Full featured.py", line 215, in do_work
    if phonenumbers.is_possible_number(phonenumbers.parse(str(IDX_PHONE))):
  File "C:\Program Files\Python39\lib\site-packages\phonenumbers\phonenumberutil.py", line 2848, in parse
    raise NumberParseException(NumberParseException.NOT_A_NUMBER,
phonenumbers.phonenumberutil.NumberParseException: (1) The string supplied did not seem to be a phone number.
2021-12-23 15:46:15,633 - ERROR - Row 5
Traceback (most recent call last):
  File "C:\Users\Matthew Curtis\Documents\Github-Pipl\Tests\Full Featured Example\Python CSV script Example - Full featured.py", line 215, in do_work
    if phonenumbers.is_possible_number(phonenumbers.parse(str(IDX_PHONE))):
  File "C:\Program Files\Python39\lib\site-packages\phonenumbers\phonenumberutil.py", line 2848, in parse
    raise NumberParseException(NumberParseException.NOT_A_NUMBER,
phonenumbers.phonenumberutil.NumberParseException: (1) The string supplied did not seem to be a phone number.
2021-12-23 15:46:15,664 - ERROR - Row 9
Traceback (most recent call last):
  File "C:\Users\Matthew Curtis\Documents\Github-Pipl\Tests\Full Featured Example\Python CSV script Example - Full featured.py", line 215, in do_work
    if phonenumbers.is_possible_number(phonenumbers.parse(str(IDX_PHONE))):
  File "C:\Program Files\Python39\lib\site-packages\phonenumbers\phonenumberutil.py", line 2848, in parse
    raise NumberParseException(NumberParseException.NOT_A_NUMBER,
phonenumbers.phonenumberutil.NumberParseException: (1) The string supplied did not seem to be a phone number.
2021-12-23 15:46:15,664 - ERROR - Row 13
Traceback (most recent call last):
  File "C:\Users\Matthew Curtis\Documents\Github-Pipl\Tests\Full Featured Example\Python CSV script Example - Full featured.py", line 215, in do_work
    if phonenumbers.is_possible_number(phonenumbers.parse(str(IDX_PHONE))):
  File "C:\Program Files\Python39\lib\site-packages\phonenumbers\phonenumberutil.py", line 2848, in parse
    raise NumberParseException(NumberParseException.NOT_A_NUMBER,
phonenumbers.phonenumberutil.NumberParseException: (1) The string supplied did not seem to be a phone number.
2021-12-23 15:46:16,530 - WARNING - Row 3 - API Warning: ZIP code `83854` was added based on street and city.

2021-12-23 15:46:16,577 - WARNING - Row 7 - API Warning: ZIP code `83854` was added based on street and city.

2021-12-23 15:46:17,479 - WARNING - Row 6 - API Warning: ZIP code `94133` was added based on street and city.

2021-12-23 15:46:17,510 - WARNING - Row 2 - API Warning: ZIP code `94133` was added based on street and city.

